### ISSUE TITLE
Suggestion: RStudio 

### ISSUE THREAD

**Issue by joshuaalley** [carlislerainey/git-for-political-science#4]
I'm new to Git, but workflow results so far are promising. The integration of Git with RStudio has been a key part of pulling everything together. It might be worthwhile to add a quick note on that function to the markdown file.

**Comment by carlislerainey** [comment]
Especially given that I work entirely in RStudio, I would like to make the doc as completely RStudio-driven as possible. Feel free to type up what you have in mind, add it to the current version, and submit a pull request. That’s my plan in the longer term, but it will probably only happen when a graduate class makes it urgent enough.

**Comment by joshuaalley** [comment]
Sounds good, I'll write something up.
